@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json

### 教師路由
GET {{baseUrl}}/teachers HTTP/1.1
Content-Type: application/json


###
GET {{baseUrl}}/teachers/1 HTTP/1.1
Content-Type: application/json


###
POST {{baseUrl}}/teachers HTTP/1.1
Content-Type: application/json

{
  "name": "judy",
  "phone": "0989898989",
	"account": "judy",
	"password": "judy1",
	"email": "judy@com.com",
	"address": "新竹市香山區食品街50號",
	"avatarImage": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/710.jpg",
	"working": true
}

###
PUT {{baseUrl}}/teachers/7 HTTP/1.1
Content-Type: application/json

{
  "name": "yui",
  "phone": "0989898989",
	"account": "judy",
	"password": "judy",
	"email": "judy@com.com",
	"address": "新竹市香山區食品街50號",
	"avatarImage": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/710.jpg",
	"working": true
}

###
DELETE  {{baseUrl}}/teachers/8 HTTP/1.1
Content-Type: application/json

###
GET {{baseUrl}}/teachers/6/courses HTTP/1.1
Content-Type: application/json

### 學生路由
GET {{baseUrl}}/students HTTP/1.1
Content-Type: application/json


###
GET {{baseUrl}}/students/1 HTTP/1.1
Content-Type: application/json


###
POST {{baseUrl}}/students HTTP/1.1
Content-Type: application/json

{
  "name": "joe",
  "phone": "0989898989",
	"account": "joe",
	"password": "joe1",
	"email": "joe@com.com",
	"address": "新竹市香山區食品街50號",
	"avatarImage": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/710.jpg",
	"learning": true
}

###
PUT {{baseUrl}}/students/8 HTTP/1.1
Content-Type: application/json

{
  "name": "yui",
  "phone": "0989898989",
	"account": "joe",
	"password": "judy",
	"email": "judy@com.com",
	"address": "新竹市香山區食品街50號",
	"avatarImage": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/710.jpg",
	"learing": true
}

###
DELETE  {{baseUrl}}/students/8 HTTP/1.1
Content-Type: application/json

###
GET {{baseUrl}}/students/5/courses HTTP/1.1
Content-Type: application/json

### 科系路由
GET {{baseUrl}}/departments HTTP/1.1
Content-Type: application/json


###
GET {{baseUrl}}/departments/1 HTTP/1.1
Content-Type: application/json


###
POST {{baseUrl}}/departments HTTP/1.1
Content-Type: application/json

{
  "name": "大地系"
}

###
PUT {{baseUrl}}/departments/21 HTTP/1.1
Content-Type: application/json

{
  "name": "火山系"
}

###
DELETE  {{baseUrl}}/departments/21 HTTP/1.1
Content-Type: application/json

### 講師開課路由
GET {{baseUrl}}/courses HTTP/1.1
Content-Type: application/json


###
GET {{baseUrl}}/courses/18 HTTP/1.1
Content-Type: application/json


###
POST {{baseUrl}}/courses HTTP/1.1
Content-Type: application/json

{
	"className" : "古典文學1",
	"classTime" : "2023-09-21 08:00:05",		
  "introduction" : "李白詩、李商隱詩、宋詩選讀、蘇辛詞、清詞選、紅樓夢",
	"departmentId" : 1,
	"teacherId" : 1
}

###
PUT {{baseUrl}}/courses/21 HTTP/1.1
Content-Type: application/json

{
	"className" : "古典文",
	"classTime" : "2023-09-21 08:00:05",		
  "introduction" : "李白詩、李商隱詩、宋詩選讀、蘇辛詞、清詞選、紅樓夢",
	"departmentId" : 1,
	"teacherId" : 1
}

###
DELETE  {{baseUrl}}/courses/21 HTTP/1.1
Content-Type: application/json
###
GET {{baseUrl}}/courses/18/students HTTP/1.1
Content-Type: application/json


### 學生選課路由
GET {{baseUrl}}/studentCourses HTTP/1.1
Content-Type: application/json


###
GET {{baseUrl}}/studentCourses/1 HTTP/1.1
Content-Type: application/json


###
POST {{baseUrl}}/studentCourses HTTP/1.1
Content-Type: application/json

{
	"className" : "古典文學1",
	"classTime" : "2023-09-21 08:00:05",		
  "introduction" : "李白詩、李商隱詩、宋詩選讀、蘇辛詞、清詞選、紅樓夢",
	"departmentId" : 1,
	"teacherId" : 1
}

###
PUT {{baseUrl}}/studentCourses/21 HTTP/1.1
Content-Type: application/json

{
	"className" : "古典文",
	"classTime" : "2023-09-21 08:00:05",		
  "introduction" : "李白詩、李商隱詩、宋詩選讀、蘇辛詞、清詞選、紅樓夢",
	"departmentId" : 1,
	"teacherId" : 1
}

###
DELETE  {{baseUrl}}/studentCourses/21 HTTP/1.1
Content-Type: application/json


###
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "name": "admin",
  "password": "Admin&8181"
}




