@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json

###
GET {{baseUrl}}/teachers HTTP/1.1
Content-Type: application/json


###
GET {{baseUrl}}/teachers/2 HTTP/1.1
Content-Type: application/json


###
POST {{baseUrl}}/teachers HTTP/1.1
Content-Type: application/json

{
  "name": "judy",
  "phone": "0989898989",
	"account": "judy",
	"password": "judy1",
	"email": "judy@com.com",
	"address": "新竹市香山區食品街50號",
	"avatar_image": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/710.jpg",
	"working": true
}

##
PUT  {{baseUrl}}/teachers HTTP/1.1
Content-Type: application/json

{
  "name": "paggy",
  "phone": "0989898989",
	"account": "judy",
	"password": "judy1",
	"email": "judy@com.com",
	"address": "新竹市香山區食品街50號",
	"avatar_image": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/710.jpg",
	"working": true
}

###
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "name": "admin",
  "password": "Admin&8181"
}




